language: python

python:
  - 3.6

cache: pip

install:
  - |
    # Stage 1: Install pytest + test dependencies
    pip install pyyaml pytest pytest-timeout pytest-xdist requests

script:
 - true

# We are using before_deploy instead of script or deploy
# since before_deploy gives us nice, folded log views,
# which neither script nor deploy seems to!
before_deploy:
- |
  # Stage 1: Install gcloud SDK
  curl -L https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-173.0.0-linux-x86_64.tar.gz | tar --directory ${HOME} --extract --gzip --file -
- |
  # Stage 1: Install Kubectl
  mkdir -p ${HOME}/bin
  curl -L https://storage.googleapis.com/kubernetes-release/release/v1.9.0/bin/linux/amd64/kubectl > ${HOME}/bin/kubectl
  chmod +x ${HOME}/bin/kubectl
- |
  # Stage 1: Install helm
  curl -L https://storage.googleapis.com/kubernetes-helm/helm-v2.7.0-linux-amd64.tar.gz | tar --directory ${HOME} --extract --gzip --file - && mv ${HOME}/linux-amd64/helm ${HOME}/bin/helm
- |
  # Stage 1: Install git-crypt
  curl -L https://github.com/minrk/git-crypt-bin/releases/download/0.5.0/git-crypt > git-crypt
  echo "46c288cc849c23a28239de3386c6050e5c7d7acd50b1d0248d86e6efff09c61b  git-crypt" | shasum -a 256 -c -
  chmod +x git-crypt
  mv git-crypt ${HOME}/bin/git-crypt
- |
  # Stage 2, Step 1: Unlock our secret files!
  # Travis allows encrypting only one file per repo (boo) so we use it to
  # encrypt our git-crypt key
  cd ${TRAVIS_BUILD_DIR}
  openssl aes-256-cbc -K $encrypted_510e3970077d_key -iv $encrypted_510e3970077d_iv -in travis/crypt-key.enc -out travis/crypt-key -d
  git-crypt unlock travis/crypt-key
  chmod 0600 secrets/*key
- |
  # Stage 2, Step 2: Set up helm!
  helm init --client-only
  helm repo add jupyterhub https://jupyterhub.github.io/helm-chart
  helm repo update
  (cd mybinder && helm dep up)
- |
  # Stage 2, Step 3: Post message to Grafana that deployment is starting
  source secrets/grafana-api-key
  export PULL_REQUEST_ID=$(git log -1 --pretty=%B | head -n1 | sed 's/^.*#\([0-9]*\).*/\1/')
  export AUTHOR_NAME="$(git log  -1 --pretty=%aN)"
  export PULL_REQUEST_TITLE="$(git log --pretty=%B -1 | tail -n+3)"
  python3 travis/post-grafana-annotation.py  \
    --grafana-url https://grafana.mybinder.org \
    --tag deployment-start \
    "$(echo -en \"${PULL_REQUEST_TITLE}\n\n${AUTHOR_NAME}: https://github.com/${TRAVIS_REPO_SLUG}/pull/${PULL_REQUEST_ID}\")"
- |
  # Stage 3, Step 1: Deploy to staging
  python ./deploy.py staging staging
- |
  # Stage 3, Step 2: Verify staging works
  py.test -n 2 --binder-url=https://staging.mybinder.org --hub-url=https://hub.staging.mybinder.org
- |
  # Stage 4, Step 1: Deploy to production
  python ./deploy.py prod prod-a
- |
  # Stage 4, Step 2: Verify production works
  py.test -n 2 --binder-url=https://mybinder.org --hub-url=https://hub.mybinder.org

env:
  global:
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
    - PATH=${HOME}/google-cloud-sdk/bin:${HOME}/bin:${PATH}

deploy:
  provider: script
  script: /bin/true
  on:
    branch:
      - master

branches:
  only:
    - master

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/2b2f3e2bfcef7f67d74a
    on_success: change
    on_failure: change
    on_error: change
    on_start: never
    on_cancel: never
