# scp me to bids.mybinder.org:/etc/kubelet.yaml
apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration
maxPods: 100
# Clean up images pulled by kubernetes anytime we are over
# 40% disk usage until we hit 20%
imageGCHighThresholdPercent: 40
imageGCLowThresholdPercent: 20
