projectName: turing


letsencrypt:
  contactEmail: drsarahlgibson@gmail.com

binderhub:
  config:
    BinderHub:
      pod_quota: 0
      hub_url: https://hub.mybinder.turing.ac.uk
      badge_base_url: https://mybinder.org
      sticky_builds: true
      # Docker Hub registry for Turing
      use_registry: true
      image_prefix: turingmybinder/binder-prod-

  replicas: 1

  ingress:
    enabled: true
    hosts:
      - binder.mybinder.turing.ac.uk
      - turing.mybinder.org
    annotations:
      kubernetes.io/ingress.class: nginx
      https:
        enabled: true
        type: nginx
    tls:
      - secretName: turing-binder-tls-crt
        hosts:
          - binder.mybinder.turing.ac.uk
          - turing.mybinder.org

  extraVolumes:
    - name: event-secret
      secret:
        secretName: events-archiver-secrets
  extraVolumeMounts:
    - name: event-secret
      mountPath: /event-secret
      readOnly: true
  extraEnv:
    - name: GOOGLE_APPLICATION_CREDENTIALS
      value: /event-secret/service-account.json

  jupyterhub:
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
        kubernetes.io/tls-acme: "true"
        https:
          enabled: true
          type: nginx
      hosts:
        - hub.mybinder.turing.ac.uk
      tls:
        - secretName: turing-hub-tls-crt
          hosts:
            - hub.mybinder.turing.ac.uk

    scheduling:
      userScheduler:
        enabled: false
      podPriority:
        enabled: true
      userPlaceholder:
        enabled: true
        replicas: 5

  imageCleaner:
    # Use 40GB as upper limit, size is given in bytes
    imageGCThresholdHigh: 40e9
    imageGCThresholdLow: 30e9
    imageGCThresholdType: "absolute"

grafana:
  ingress:
    annotations:
      kubernetes.io/ingress.class: nginx
      kubernetes.io/tls-acme: 'true'
    hosts:
      - grafana.mybinder.turing.ac.uk
    tls:
      - secretName: turing-grafana-tls-crt
        hosts:
          - grafana.mybinder.turing.ac.uk
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
        - name: prometheus
          orgId: 1
          type: prometheus
          url: https://prometheus.mybinder.turing.ac.uk
          access: direct
          isDefault: true
          editable: false
  persistence:
    storageClassName: default

prometheus:
  server:
    ingress:
      annotations:
        kubernetes.io/ingress.class: nginx
        kubernetes.io/tls-acme: 'true'
      hosts:
        - prometheus.mybinder.turing.ac.uk
        - prometheus.turing.mybinder.org
      tls:
        - hosts:
            - prometheus.mybinder.turing.ac.uk
            - prometheus.turing.mybinder.org
          secretName: turing-prometheus-tls-crt
    persistentVolume:
      size: 16Gi

ingress-nginx:
  controller:
    service:
      loadBalancerIP: 51.138.65.80


static:
  ingress:
    hosts:
      - static.mybinder.turing.ac.uk
    tls:
      secretName: turing-static-tls-crt

redirector:
  redirects:
    - type: host
      host:
        from: docs-mybinder.turing.10.0.0.1.xip.io
        to: mybinder.readthedocs.io

matomo:
  enabled: false

analyticsPublisher:
  enabled: false

gcsProxy:
  enabled: false
