# scp me to staging.ovh.mybinder.org:/var/lib/rancher/k3s/agent/etc/kubelet.conf.d/99-kubelet.conf
apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration
maxPods: 50
# Clean up images pulled by kubernetes anytime we are over
# 40% disk usage until we hit 20%
imageGCHighThresholdPercent: 40
imageGCLowThresholdPercent: 20
