name: Prune harbor

on:
  schedule:
    # Run at 03:00 every Sunday, ref: https://crontab.guru/#0_3_*_*_0
    - cron: "0 3 * * 0"
  workflow_dispatch:

# only allow one prune at a time
concurrency: prune-harbor

jobs:
  prune-harbor:
    name: Prune ${{ matrix.name }} harbor registry
    runs-on: ubuntu-22.04
    if: github.repository_owner == 'jupyterhub'

    strategy:
      fail-fast: false
      matrix:
        include:
          - name: ovh2

    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-python@v6
        with:
          python-version: "3.10"

      - name: "Install dependencies"
        run: |
          pip install --upgrade setuptools pip
          pip install requests ruamel.yaml tqdm

      - name: "Unlock git-crypt secrets"
        uses: sliteteam/github-action-git-crypt-unlock@f99c0c6b60bb7ec30dcec033a8f0a3b3d48f21e1
        env:
          GIT_CRYPT_KEY: ${{ secrets.GIT_CRYPT_KEY }}

      - name: Prune registry
        run: |
          python3 scripts/prune_harbor.py ${{ matrix.name }}
